version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mysql
    command: sh -c "sleep 5 && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'doublevpartners'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
